name: Build for Staging

on:
  push:
    branches:
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      profile: staging
      build-type: apk
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}