name: Build for Development

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow.yml@${{ github.ref_name }}
    with:
      environment: development
      buildType: apk
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}