name: Build for Testing

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      profile: testing
      build-type: apk
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}