name: Build for Development

on:
  push:
    branches:
      - feature/*

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Android env
        uses: ./.github/actions/build-environment
        with:
          platform: 'android'
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i

      - name: Build Android app
        run: eas build --platform android --profile development --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: ${{ github.workspace }}/app-release.apk

  ios-build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up iOS env
        uses: ./.github/actions/build-environment
        with:
          platform: 'ios'
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: pnpm i

      - name: Build iOS app
        run: eas build --platform ios --profile development --local --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: ${{ github.workspace }}/app-release.ipa

