name: Build for Production

on:
  push:
    branches:
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      profile: production
      build-type: aab
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}