name: Build for Development

on:
  push:
    branches:
      - feature/*  # 监听 feature/** 分支的推送事件
  pull_request:
    branches:
      - feature/*  # 监听针对 feature/* 分支的 PR

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Create Gradle properties file
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=2g" > ~/.gradle/gradle.properties

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i

      - name: Build Android app
        run: eas build --platform android --profile development --local --output ${{ github.workspace }}/app-development.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-development
          path: ${{ github.workspace }}/app-release.apk

  ios-build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i
      
      - name: Build iOS app
        run: eas build --platform ios --profile development --local --output ${{ github.workspace }}/app-development.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa

