name: EAS Build

on:
  push:
    branches:
      - feature/*
      - release/*

  workflow_dispatch:
    inputs:
      platform:
        description: 'Select the platform to build (android, ios, or all)'
        required: true
        default: 'all'
        options:
          - android
          - ios
          - all
      profile:
        description: 'Select the build profile'
        required: true
        default: 'development'
        options:
          - development
          - testing
          - staging
          - production



jobs:
  validate-input:
    runs-on: ubuntu-latest

    steps:
      - name: Validate profile for feature/* branch
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          if [[ "${{ inputs.profile }}" != "development" && "${{ inputs.profile }}" != "testing" ]]; then
            echo "Error: Only 'development' and 'testing' profiles are allowed for feature/* branches."
            exit 1
          fi

      - name: Validate profile for release/* branch
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          if [[ "${{ inputs.profile }}" != "staging" && "${{ inputs.profile }}" != "production" ]]; then
            echo "Error: Only 'staging' and 'production' profiles are allowed for release/* branches."
            exit 1
          fi
    
  android-build:
    name: Build Android APK
    needs: validate-input
    runs-on: ubuntu-latest
    if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i
      
      - name: Determine build profile
        id: profile
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "profile=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "testing" ]]; then
            echo "profile=testing" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "profile=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            echo "profile=production" >> $GITHUB_ENV
          fi

      - name: Build Android app
        env:
          EAS_PROFILE: ${{ env.profile }}
        run: eas build --platform android --profile $EAS_PROFILE --local --output ${{ github.workspace }}/app-development.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-development-android
          path: ${{ github.workspace }}/app-development.apk

  ios-build:
    name: Build iOS IPA
    needs: validate-input
    runs-on: macos-latest
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i
      
      - name: Determine build profile
        id: profile
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "profile=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "testing" ]]; then
            echo "profile=testing" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "profile=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            echo "profile=production" >> $GITHUB_ENV
          fi

      - name: Build Android app
        env:
          EAS_PROFILE: ${{ env.profile }}
        run: eas build --platform ios --profile $EAS_PROFILE --local --output ${{ github.workspace }}/app-development.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-development-ios
          path: ${{ github.workspace }}/app-development.ipa

