name: Reusable Expo OTA Updates Workflow  

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        description: 'An API acesss token for Expo'

jobs:
  update:
    name: Expo Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Check fingerprint
        id: fingerprint
        uses: expo/expo-github-action/fingerprint@main

      - name: Display fingerprint
        run: echo "iOS fingerprint is ${{ steps.fingerprint.outputs.current-fingerprint }}"
