name: Reusable Expo OTA Updates Workflow  

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        description: 'An API acesss token for Expo'

jobs:
  anroid-update:
    name: Expo Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Exported bundles
        run: pnpm exec expo export --platform android

      - name: Computed project fingerprints
        run: |
          echo "android-fingerprint=$(pnpm exec expo-updates fingerprint:generate --platform android | jq -r '.hash')" >> $GITHUB_ENV
          echo "Android fingerprint is ${{ env.android-fingerprint }}"
      
      - name: Uploaded bundles
        run: echo "Uploaded bundles"
      
  ios-update:
    name: Expo Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Exported bundles
        run: pnpm exec expo export --platform ios

      - name: Computed project fingerprints
        run: |
          echo "ios-fingerprint=$(pnpm exec expo-updates fingerprint:generate --platform ios | jq -r '.hash')" >> $GITHUB_ENV
          echo "iOS fingerprint is ${{ env.ios-fingerprint }}"
      
      - name: Uploaded bundles
        run: echo "Uploaded bundles"
      

